### ISSUE TITLE
Passing names as a filter argument does not work for storage location filter

### ISSUE THREAD

**Issue by syed1992** [V0RT3X4/python-sdk#141]
![image](https://user-images.githubusercontent.com/45287337/71664721-effa9880-2d51-11ea-92e4-e96bfbf55c11.png)

**Comment by kujon** [comment]
@syed1992 we have removed this functionality here https://github.com/V0RT3X4/python-sdk/pull/134. Long story short, when searching by name, the search requests resolves to IDs in the background. We do a fuzzy search behind the scenes, so e.g. searching for 'India', would include 'Indiana' as well, and the user would have no visibility into why they're getting incorrect results. The alternative would be to do the exact matching, but that would default the point of having user-friendly search, if you have to type e.g. 'Service Terminal Rotterdam (STR)' exactly.

We'll most likely re-introduce this feature as an additional `fuzzy_search` method to make this behaviour explicit. We'd also return the resolved geographies/products/etc. in the response to tell you exactly what has been matched.
