### ISSUE TITLE
How to ensure the right entity is isolated when sending a query parameter by name

### ISSUE THREAD

**Issue by syed1992** [V0RT3X4/python-sdk#35]
![image](https://user-images.githubusercontent.com/45287337/69068626-02787700-0a1d-11ea-89e8-f79ae4b24aeb.png)
new challenge that arises from allowing user to enter a parameter by name, the current functionality matches the strings to all possible entities - this can lead to unwanted entities being selected as above

**Comment by KitBurgess** [comment]
Closing this as it's a duplicate of #37
