### ISSUE TITLE
What are the default parameters used in the absence of an explicit value

### ISSUE THREAD

**Issue by syed1992** [V0RT3X4/python-sdk#42]
![image](https://user-images.githubusercontent.com/45287337/69078205-42485a00-0a2f-11ea-864c-134b887d8287.png)
although default parameters are shown in the docs, this is not made clear enough to the user. 

This could be highlighted more explicitly in the docs

**Comment by KitBurgess** [comment]
Default parameters are given here: 
![image](https://user-images.githubusercontent.com/33626692/69528767-cb4b1e00-0f66-11ea-9e82-97cd7dd253e3.png)

In future, we could look into expanding the search bar, but I don't think this should be prioritised over other docs issues now.
