### ISSUE TITLE
change default column 'events.cargo_port_load_event.0.start_timestamp' to 'events.cargo_port_load_event.0.end_timestamp'

### ISSUE THREAD

**Issue by syed1992** [V0RT3X4/python-sdk#56]
This is to align dates with our convention of departures and arrivals i.e. loading_end and unloading_start

**Comment by KitBurgess** [comment]
Should the `events.cargo_port_unload_event.0.start_timestamp` also be changed to `events.cargo_port_unload_event.0.end_timestamp`?

**Comment by syed1992** [comment]
I think `events.cargo_port_unload_event.0.start_timestamp` should stay the same because we count our arrivals as `unloading_start`
