### ISSUE TITLE
Do we need to hide these internal modules?

### ISSUE THREAD

**Issue by KitBurgess** [V0RT3X4/python-sdk#67]
What do other libraries do?

![image](https://user-images.githubusercontent.com/33626692/69434420-82f8e980-0d35-11ea-90ac-021143a4e917.png)

**Comment by cvonsteg** [comment]
Short answer - you cannot fully hide these.  There is no such thing as truly private in python.  We could alter the folder structure, so that these aren't all immediately loaded by tabbing the `vortexasdk` module, but anybody will still be able to access them if they know the file structure.
