### ISSUE TITLE
Consider adopting All Contributors specification

### ISSUE THREAD

**Issue by kujon** [V0RT3X4/python-sdk#98]
https://allcontributors.org/

Let's recognise all contributions, code or not.

**Comment by KitBurgess** [comment]
@all-contributors bot add @KitBurgess for design, code

**Comment by KitBurgess** [comment]
@kujon the docs page looks like this below:

![image](https://user-images.githubusercontent.com/33626692/69817856-6a844580-11f3-11ea-8670-9d7bcc175852.png)

**Comment by kujon** [comment]
Yeah, awesome!

**Comment by KitBurgess** [comment]
@all-contributors bot add @cvonsteg for code, review

**Comment by KitBurgess** [comment]
@all-contributors bot add @syed1992 for review

**Comment by KitBurgess** [comment]
@all-contributors bot add @dstarkey23 for code, docs, examples

**Comment by KitBurgess** [comment]
Adds @dstarkey23 as a contributor for code, doc, example.

**Comment by KitBurgess** [comment]
@all-contributors bot add @dstarkey23 as a contributor for code, doc, example.

**Comment by KitBurgess** [comment]
@all-contributors bot add @syed1992 for review

**Comment by KitBurgess** [comment]
@all-contributors bot add @syed1992 for review
